<a href="https://colab.research.google.com/github/svenzer007/Linear-regression/blob/main/ex1_scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [23]:
def normalize(X):
  for i in range(X.shape[1]):
    a = X[:,i]
    m = np.mean(a)
    s = np.std(a)
    a = (1.*a-m)/s
    X[:,i] = a
  return X

In [38]:
data = pd.read_csv('/content/ex1data2.txt')
data = data.to_numpy()
X = data[:,0:2]
Y = data[:,2]
X = X.astype('float64')
Y = Y.astype('float64')
print(np.mean(X[:,0]),np.mean(X[:,1]),np.std(X[:,0]),np.std(X[:,1]))
X = normalize(X)
X = np.hstack((np.ones((X.shape[0],1)),X))
print(X)

1998.4347826086957 3.1739130434782608 794.5531599632346 0.7605589428059087
[[ 1.00000000e+00 -5.01457678e-01 -2.28664780e-01]
 [ 1.00000000e+00  5.05397546e-01 -2.28664780e-01]
 [ 1.00000000e+00 -7.33034380e-01 -1.54348727e+00]
 [ 1.00000000e+00  1.26053896e+00  1.08615771e+00]
 [ 1.00000000e+00 -1.69086013e-02  1.08615771e+00]
 [ 1.00000000e+00 -5.84523234e-01 -2.28664780e-01]
 [ 1.00000000e+00 -7.19190120e-01 -2.28664780e-01]
 [ 1.00000000e+00 -7.78342865e-01 -2.28664780e-01]
 [ 1.00000000e+00 -6.34865995e-01 -2.28664780e-01]
 [ 1.00000000e+00 -7.35442077e-02  1.08615771e+00]
 [ 1.00000000e+00  1.96993413e-03 -2.28664780e-01]
 [ 1.00000000e+00 -1.36472659e-01 -2.28664780e-01]
 [ 1.00000000e+00  3.12070399e+00  2.40098019e+00]
 [ 1.00000000e+00 -9.19302596e-01 -2.28664780e-01]
 [ 1.00000000e+00  3.79540643e-01  1.08615771e+00]
 [ 1.00000000e+00 -8.53857006e-01 -1.54348727e+00]
 [ 1.00000000e+00 -9.59576805e-01 -2.28664780e-01]
 [ 1.00000000e+00  7.68438474e-01  1.08615771e+00]
 [ 1.00

In [37]:
reg = LinearRegression().fit(X,Y)
theta = reg.coef_
print(np.dot(np.array([[1,(1650-1998.4347826086957)/(794.5531599632346),(3-3.1739130434782608)/(0.7605589428059087)]]),theta))
print(reg.coef_,reg.intercept_)
print(reg.predict(np.array([[1,(1650-1998.4347826086957)/(794.5531599632346),(3-3.1739130434782608)/(0.7605589428059087)]])))

[110248.92165868  -6226.22670553] 339119.45652173914
